--INSERT INTO BEBIDA VALUES(1, 'Coca Cola', 5.0);
--INSERT INTO BEBIDA VALUES(2, 'Fanta', 5.0);

--INSERT INTO PIZZA VALUES (1, 'Mussarela', 35.0);
--INSERT INTO PIZZA VALUES (2, 'Calabresa', 30.0);

--INSERT INTO PEDIDO_PIZZA_DELIVERY VALUES (1, 'Caucaia', 'blabla', '2020-10-01', 'pitas', 58);



--INSERT INTO PIZZA_PEDIDO_DELIVERY  VALUES (1,1);
--INSERT INTO PIZZA_PEDIDO_DELIVERY  VALUES (2,1);

--INSERT INTO BEBIDA_PEDIDO_DELIVERY  VALUES (2,1);
--INSERT INTO BEBIDA_PEDIDO_DELIVERY  VALUES (1,1);

--INSERT INTO PIZZA_DELIVERY VALUES (1, 1, 1, 1);
--INSERT INTO PIZZA_DELIVERY VALUES (2, 2, 1, 2);


