name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        run: |
          echo "---------| buildando app | -----------"
          mvn clean package
          echo "---------| gerando build | -----------"
          docker build -t=uniliva/app-sodre:latest .
          echo "---------| enviando docker hub | -----------"
          docker push uniliva/app-sodre:latest
          echo "---------| Sucessão | -----------"
